[versions]
kotlin = "[2.1,3.0)"
ktlint = "[12.1,13.0)"
shadow = "[8.3,9.0)"
jreleaser = "[1.16,2.0)"
bytedecoJavacvPlatform = "[1.5,2.0)"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }

[libraries]
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }

bytedeco-javacv-platform = { group = "org.bytedeco", name = "javacv-platform", version.ref = "bytedecoJavacvPlatform" }
