[versions]
kotlin = "[2.4,3.0)"
ktlint = "[14.2,15.0)"
shadow = "[9.6,10.0)"
jreleaser = "[1.26,2.0)"
kotlinxCoroutinesCore = "[1.11,2.0)"
wsSchild = "[4.2,5.0)"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }

[libraries]
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }

ws-schild-jave-all-deps = { group = "ws.schild", name = "jave-all-deps", version.ref = "wsSchild" }
